'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Sparkles, Bot, Network, ArrowUpRight, CheckCircle2, RotateCcw, Play, Zap, Cpu, ShieldCheck, Database } from 'lucide-react';
import { aiTopics } from '../data/topics';

const SAMPLE_QUERIES = [
  {
    id: 'sla',
    query: 'What is our enterprise SLA for Sev-1 critical outages?',
    chunks: [
      { id: 'c1', text: 'Enterprise Tier SLA guarantees 15-minute response time and 99.99% uptime for Sev-1 outages.', score: 0.96, source: 'legal_sla_2026.md' },
      { id: 'c2', text: 'Sev-1 escalations automatically trigger PagerDuty rotation to On-Call Principal Engineers.', score: 0.88, source: 'incident_runbook.md' },
    ],
    answer: 'According to our enterprise legal contract [legal_sla_2026.md], Sev-1 critical outages carry a **15-minute initial response SLA** with a guaranteed **99.99% annual uptime commitment**.'
  },
  {
    id: 'kms',
    query: 'How often are AWS KMS root encryption keys automatically rotated?',
    chunks: [
      { id: 'c1', text: 'AWS KMS customer managed keys are configured for automatic annual rotation every 365 days.', score: 0.94, source: 'security_compliance.md' },
      { id: 'c2', text: 'Envelope encryption uses AES-256 data keys generated by KMS HSMs.', score: 0.81, source: 'crypto_architecture.md' },
    ],
    answer: 'AWS KMS customer managed keys undergo **automatic key rotation every 365 days (1 year)** without re-encrypting existing ciphertext [security_compliance.md].'
  },
  {
    id: 'refund',
    query: 'What is the return policy for opened hardware devices?',
    chunks: [
      { id: 'c1', text: 'Hardware items may be returned within 30 days of delivery with a 15% restocking fee if packaging is opened.', score: 0.92, source: 'return_policy.md' },
      { id: 'c2', text: 'Defective hardware is replaced immediately with expedited shipping under standard 1-year warranty.', score: 0.85, source: 'warranty_terms.md' },
    ],
    answer: 'Opened hardware devices can be returned within **30 days of delivery**, subject to a **15% restocking fee** [return_policy.md].'
  }
];

export function Home() {
  const [selectedQuery, setSelectedQuery] = useState(SAMPLE_QUERIES[0]);
  const [activeStep, setActiveStep] = useState<number>(0);
  const [isProcessing, setIsProcessing] = useState<boolean>(false);

  const runPipeline = () => {
    setIsProcessing(true);
    setActiveStep(1); // Vectorizing

    setTimeout(() => {
      setActiveStep(2); // Vector Search HNSW
      setTimeout(() => {
        setActiveStep(3); // Re-ranking
        setTimeout(() => {
          setActiveStep(4); // LLM Synthesis
          setIsProcessing(false);
        }, 400);
      }, 400);
    }, 400);
  };

  const resetAll = () => {
    setActiveStep(0);
    setIsProcessing(false);
  };

  return (
    <div className="space-y-24 pb-20">
      {/* Hero Section */}
      <section className="relative pt-12 md:pt-20 px-6 max-w-7xl mx-auto">
        <div className="ai-grid-bg absolute inset-0 -z-10 rounded-3xl opacity-60" />

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          {/* Left Hero Copy */}
          <div className="lg:col-span-7 space-y-6">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-[var(--ai-primary)]/30 bg-[var(--ai-primary)]/10 text-[var(--ai-primary)] text-xs font-mono">
              <Sparkles className="w-3.5 h-3.5 animate-pulse text-[var(--ai-primary)]" />
              RAG &bull; Autonomous Agents &bull; Vector Databases &bull; Guardrails
            </div>

            <h1 className="font-display text-5xl md:text-7xl font-extrabold tracking-tight leading-[1.05] text-[var(--ai-text)]">
              Grounded Retrieval.<br />
              <span className="text-[var(--ai-primary)] ai-glow">Enterprise RAG &amp;</span> Autonomous Agents.
            </h1>

            <p className="text-base md:text-lg text-[var(--ai-muted)] max-w-xl leading-relaxed">
              Master modern AI Application Engineering. Explore high-dimensional vector search, Cross-Encoder re-ranking, autonomous ReAct agent loops, and the RAG Triad evaluation framework.
            </p>

            <div className="flex flex-wrap items-center gap-4 pt-4">
              <Link
                href="/aicosmos/learn"
                className="inline-flex items-center gap-2 px-6 py-3.5 rounded-lg bg-[var(--ai-primary)] text-white font-semibold text-sm hover:bg-[var(--ai-primary-hover)] transition-all shadow-[0_0_20px_rgba(99,102,241,0.35)] active:scale-95"
              >
                Explore Concept Map <ArrowRight className="w-4 h-4" />
              </Link>
              
              <Link
                href="/aicosmos/rag-lab"
                className="inline-flex items-center gap-2 px-6 py-3.5 rounded-lg border border-[var(--ai-border)] bg-[var(--ai-surface)] text-[var(--ai-text)] font-mono text-sm hover:border-[var(--ai-primary)] hover:text-[var(--ai-primary)] transition-all"
              >
                <Network className="w-4 h-4 text-[var(--ai-cyan)]" />
                RAG Lab
              </Link>

              <Link
                href="/aicosmos/agent-lab"
                className="inline-flex items-center gap-2 px-6 py-3.5 rounded-lg border border-[var(--ai-border-subtle)] bg-[var(--ai-surface-2)] text-[var(--ai-muted)] font-mono text-sm hover:text-[var(--ai-text)] transition-all"
              >
                <Bot className="w-4 h-4 text-[var(--ai-amber)]" />
                ReAct Agent Lab
              </Link>
            </div>
          </div>

          {/* Right Live RAG Pipeline Simulator */}
          <div className="lg:col-span-5">
            <div className="rounded-2xl border border-[var(--ai-border)] bg-[var(--ai-surface)] shadow-2xl overflow-hidden font-mono text-xs">
              <div className="px-4 py-3 border-b border-[var(--ai-border-subtle)] bg-[var(--ai-surface-2)] flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 rounded-full bg-red-500/80" />
                  <div className="w-3 h-3 rounded-full bg-yellow-500/80" />
                  <div className="w-3 h-3 rounded-full bg-green-500/80" />
                  <span className="text-xs text-[var(--ai-muted)] ml-2">RAG::PipelineStudio</span>
                </div>
                <button
                  onClick={resetAll}
                  className="text-[10px] text-[var(--ai-muted)] hover:text-[var(--ai-primary)]"
                  title="Reset"
                >
                  <RotateCcw className="w-3 h-3" />
                </button>
              </div>

              <div className="p-6 space-y-6">
                {/* Query Selector */}
                <div className="space-y-1.5">
                  <span className="text-[10px] text-[var(--ai-muted)]">Select Enterprise Query:</span>
                  <div className="space-y-2">
                    {SAMPLE_QUERIES.map((sq) => (
                      <button
                        key={sq.id}
                        onClick={() => { setSelectedQuery(sq); setActiveStep(0); }}
                        className={`w-full p-2.5 rounded-lg border text-left transition-all ${
                          selectedQuery.id === sq.id
                            ? 'border-[var(--ai-primary)] bg-[var(--ai-primary)]/15 text-white font-bold'
                            : 'border-[var(--ai-border-subtle)] bg-[var(--bu-bg)] text-[var(--ai-muted)]'
                        }`}
                      >
                        {sq.query}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Pipeline Steps Indicator */}
                <div className="grid grid-cols-4 gap-1 text-[9px] text-center">
                  {[
                    ['1. Vectorize', 1],
                    ['2. HNSW Search', 2],
                    ['3. Re-Rank', 3],
                    ['4. LLM Synthesis', 4]
                  ].map(([label, stepNum]) => {
                    const isDone = activeStep >= (stepNum as number);
                    return (
                      <div
                        key={label as string}
                        className={`p-1.5 rounded border transition-all ${
                          isDone
                            ? 'border-[var(--ai-primary)] bg-[var(--ai-primary)]/20 text-indigo-300 font-bold'
                            : 'border-[var(--ai-border-subtle)] bg-black/20 text-[var(--ai-muted)]'
                        }`}
                      >
                        {label}
                      </div>
                    );
                  })}
                </div>

                {/* Retrieved Chunks Preview */}
                {activeStep >= 3 && (
                  <div className="p-3 rounded-xl bg-[var(--ai-bg)] border border-[var(--ai-border-subtle)] space-y-2 text-[10px]">
                    <span className="text-[var(--ai-cyan)] font-bold uppercase tracking-wider block">
                      Retrieved Context ({selectedQuery.chunks.length} chunks)
                    </span>
                    {selectedQuery.chunks.map((c, i) => (
                      <div key={i} className="p-2 rounded border border-white/5 bg-white/[0.02] space-y-1">
                        <div className="flex justify-between text-[9px] text-[var(--ai-muted)]">
                          <span>{c.source}</span>
                          <span className="text-emerald-400 font-bold">Cosine: {c.score}</span>
                        </div>
                        <p className="text-[var(--ai-muted)] leading-relaxed">{c.text}</p>
                      </div>
                    ))}
                  </div>
                )}

                {/* LLM Synthesis Output */}
                {activeStep === 4 && (
                  <div className="p-4 rounded-xl border border-emerald-500/40 bg-emerald-500/10 space-y-2">
                    <span className="text-emerald-400 font-bold uppercase text-[9px] tracking-wider block">
                      ✓ Grounded LLM Response (Zero Hallucination)
                    </span>
                    <p className="text-[11px] text-emerald-200 leading-relaxed font-sans">
                      {selectedQuery.answer}
                    </p>
                  </div>
                )}

                {/* Trigger Button */}
                <button
                  onClick={runPipeline}
                  disabled={isProcessing}
                  className="w-full py-3 rounded-lg bg-[var(--ai-primary)] text-white font-bold hover:bg-[var(--ai-primary-hover)] transition-all shadow-md active:scale-95 disabled:opacity-40 flex items-center justify-center gap-2"
                >
                  <Play className="w-3.5 h-3.5 fill-white" />
                  {isProcessing ? 'Executing RAG Pipeline...' : 'Execute RAG Retrieval'}
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* RAG Triad Evaluation Grid */}
      <section className="max-w-7xl mx-auto px-6 space-y-12">
        <div className="text-center space-y-4 max-w-2xl mx-auto">
          <div className="inline-flex items-center gap-2 text-xs font-mono text-[var(--ai-primary)] uppercase tracking-wider">
            <ShieldCheck className="w-4 h-4" /> Production Quality Assurance
          </div>
          <h2 className="font-display text-3xl md:text-5xl font-bold tracking-tight text-[var(--ai-text)]">
            The RAG Triad Evaluation Framework
          </h2>
          <p className="text-sm text-[var(--ai-muted)]">
            The mathematical gold standard for benchmarking enterprise retrieval-augmented generation systems.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 font-mono text-xs">
          {/* Context Relevance */}
          <div className="p-8 rounded-2xl border border-cyan-500/30 bg-[var(--ai-surface)] space-y-6">
            <div className="flex items-center justify-between">
              <span className="font-display font-bold text-xl text-[var(--ai-text)]">1. Context Relevance</span>
              <span className="text-[10px] px-2 py-1 rounded bg-cyan-500/10 text-cyan-400 border border-cyan-500/20 font-bold">
                RETRIEVAL
              </span>
            </div>
            <p className="text-xs text-[var(--ai-muted)] leading-relaxed font-sans">
              Measures the precision of the vector retriever: does the retrieved document context contain the necessary facts while eliminating noise?
            </p>
            <div className="p-4 rounded-lg bg-[var(--ai-bg)] space-y-1 text-[10px] text-[var(--ai-muted)] border border-cyan-500/20">
              <span className="text-cyan-400 font-bold">Target Metric: &gt; 0.90 Relevance</span>
              <div>• Evaluated via Cross-Encoder score</div>
            </div>
          </div>

          {/* Groundedness */}
          <div className="p-8 rounded-2xl border border-emerald-500/30 bg-[var(--ai-surface)] space-y-6">
            <div className="flex items-center justify-between">
              <span className="font-display font-bold text-xl text-[var(--ai-text)]">2. Groundedness</span>
              <span className="text-[10px] px-2 py-1 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-bold">
                NO HALLUCINATION
              </span>
            </div>
            <p className="text-xs text-[var(--ai-muted)] leading-relaxed font-sans">
              Verifies that every single atomic claim in the LLM answer is strictly backed by the retrieved context chunks without fabrication.
            </p>
            <div className="p-4 rounded-lg bg-[var(--ai-bg)] space-y-1 text-[10px] text-[var(--ai-muted)] border border-emerald-500/20">
              <span className="text-emerald-400 font-bold">Target Metric: &gt; 0.98 Grounded</span>
              <div>• Zero hallucinated claims allowed</div>
            </div>
          </div>

          {/* Answer Relevance */}
          <div className="p-8 rounded-2xl border border-indigo-500/30 bg-[var(--ai-surface)] space-y-6">
            <div className="flex items-center justify-between">
              <span className="font-display font-bold text-xl text-[var(--ai-text)]">3. Answer Relevance</span>
              <span className="text-[10px] px-2 py-1 rounded bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 font-bold">
                INTENT MATCH
              </span>
            </div>
            <p className="text-xs text-[var(--ai-muted)] leading-relaxed font-sans">
              Ensures the final response directly satisfies the user original intent without evasion, excessive verbosity, or irrelevant digressions.
            </p>
            <div className="p-4 rounded-lg bg-[var(--ai-bg)] space-y-1 text-[10px] text-[var(--ai-muted)] border border-indigo-500/20">
              <span className="text-indigo-400 font-bold">Target Metric: &gt; 0.92 Relevance</span>
              <div>• Semantic embedding query alignment</div>
            </div>
          </div>
        </div>
      </section>

      {/* Featured Topics Grid */}
      <section className="max-w-7xl mx-auto px-6 space-y-12">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 border-b border-[var(--ai-border-subtle)] pb-6">
          <div>
            <div className="text-xs font-mono text-[var(--ai-primary)] uppercase tracking-wider">
              Architecture Tracks
            </div>
            <h2 className="font-display text-3xl font-bold tracking-tight text-[var(--ai-text)] mt-1">
              AI Engineering Core Modules
            </h2>
          </div>
          <Link
            href="/aicosmos/learn"
            className="inline-flex items-center gap-2 text-xs font-mono text-[var(--ai-primary)] hover:underline"
          >
            View all 5 topics <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {aiTopics.map((topic) => (
            <Link
              key={topic.id}
              href={`/aicosmos/learn/${topic.id}`}
              className="ai-card p-6 rounded-xl space-y-4 group"
            >
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-mono uppercase tracking-widest text-[var(--ai-primary)]">
                  {topic.kicker}
                </span>
                <ArrowUpRight className="w-4 h-4 text-[var(--ai-muted)] group-hover:text-[var(--ai-primary)] group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-all" />
              </div>

              <h3 className="font-display font-bold text-lg text-[var(--ai-text)] group-hover:text-[var(--ai-primary)] transition-colors">
                {topic.title}
              </h3>

              <p className="text-xs text-[var(--ai-muted)] leading-relaxed line-clamp-2">
                {topic.summary}
              </p>

              <div className="pt-2 flex items-center gap-2">
                <span className="text-[10px] font-mono px-2 py-0.5 rounded border border-[var(--ai-border-subtle)] text-[var(--ai-muted)]">
                  {topic.difficulty}
                </span>
                <span className="text-[10px] font-mono text-[var(--ai-muted)]">
                  {topic.group}
                </span>
              </div>
            </Link>
          ))}
        </div>
      </section>
    </div>
  );
}
