export interface AiTopic {
  id: string;
  title: string;
  kicker: string;
  group: 'Vector Databases' | 'RAG Architectures' | 'AI Agents' | 'Prompt Engineering' | 'Evaluation & Guardrails';
  difficulty: 'starter' | 'intermediate' | 'advanced' | 'expert';
  summary: string;
  definition: string;
  analogy: string;
  steps: string[];
  mistakes: string[];
  optimization: string;
  codeSnippet: string;
  outputDescription: string;
  related: string[];
}

export interface AiTopicGroup {
  id: string;
  name: string;
  description: string;
  badgeColor: string;
  topics: AiTopic[];
}

export const aiTopics: AiTopic[] = [
  // 1. Vector Databases
  {
    id: 'vector-embeddings-hnsw-indexing',
    title: 'Vector Embeddings & HNSW Similarity Search',
    kicker: 'Vector Search / 01',
    group: 'Vector Databases',
    difficulty: 'starter',
    summary: 'Transforming unstructured text into 1,536-dimensional floating point vectors and performing sub-millisecond approximate nearest neighbor (ANN) lookups with HNSW.',
    definition: 'Vector Embeddings map semantic concepts into dense high-dimensional geometric spaces (e.g. OpenAI text-embedding-3-small with 1,536 dimensions), where semantically similar texts have high Cosine Similarity. Hierarchical Navigable Small World (HNSW) graphs organize vectors into multi-layer skip-list graph structures to achieve O(log N) nearest neighbor search over millions of embeddings.',
    analogy: 'A multi-story library where books are shelved not alphabetically, but by conceptual meaning. To find a book on "astrophysics", you enter the top floor (express highway) and zoom down specific staircases (HNSW layers) until landing on the exact shelf cluster.',
    steps: [
      'Text Chunking: Split documents into 512-token chunks with 50-token semantic overlap',
      'Vector Embedding: Model converts text chunk into 1,536-dimensional normalized float array',
      'HNSW Graph Construction: Vector inserted into multi-layer graph with proximity edges (M=16, efConstruction=200)',
      'Query Vectorization: User prompt converted into query vector',
      'ANN Beam Search: Graph traversal hops across nearest nodes in Euclidean / Cosine space to return top-k matches'
    ],
    mistakes: [
      'Using flat brute-force search over millions of vectors in production (O(N) search causes 500ms+ latency spikes)',
      'Comparing vectors generated by different embedding models (vector spaces are completely incompatible)'
    ],
    optimization: 'Scalar Quantization (SQ8) compresses 32-bit float vectors to 8-bit integers, reducing RAM usage by 75% with less than 1% recall loss.',
    codeSnippet: `// Vector Similarity Calculation & Embedding Search
import { cosineSimilarity } from 'ai-vector-math';

export interface VectorDocument {
  id: string;
  text: string;
  embedding: number[]; // 1536-dim vector
}

export class VectorStore {
  private docs: VectorDocument[] = [];

  add(doc: VectorDocument) { this.docs.push(doc); }

  search(queryVector: number[], topK: number = 3): VectorDocument[] {
    return [...this.docs]
      .map(doc => ({
        doc,
        similarity: cosineSimilarity(queryVector, doc.embedding)
      }))
      .sort((a, b) => b.similarity - a.similarity)
      .slice(0, topK)
      .map(item => item.doc);
  }
}`,
    outputDescription: 'Computes top-k semantic similarity matches over high-dimensional vector embeddings.',
    related: ['advanced-rag-retrieval-reranking', 'react-agents-tool-calling', 'evaluation-hallucination-guardrails']
  },

  // 2. RAG Architectures
  {
    id: 'advanced-rag-retrieval-reranking',
    title: 'Advanced RAG: Hybrid Search, Chunking & Cross-Encoder Re-Ranking',
    kicker: 'RAG Pipeline / 01',
    group: 'RAG Architectures',
    difficulty: 'intermediate',
    summary: 'Building high-precision Retrieval-Augmented Generation pipelines using BM25 keyword + Dense vector hybrid search, followed by Cross-Encoder re-ranking.',
    definition: 'Retrieval-Augmented Generation (RAG) augments LLM prompts with dynamic external factual context. Advanced RAG combines Dense Vector Search (semantic capture) with Sparse BM25 Search (exact keyword/identifier matches via Reciprocal Rank Fusion), followed by a Cross-Encoder Re-Ranker model that scores query-document relevance jointly before LLM synthesis.',
    analogy: 'An expert trial attorney: instead of relying solely on memory, the attorney searches legal archives using both keyword indexes (BM25) and conceptual case law (Vector Search), filters out 90% of irrelevant filings (Re-ranking), and presents the top 3 precedents directly to the judge.',
    steps: [
      'Hybrid Retrieval: Concurrently execute BM25 keyword search and Dense vector search',
      'Reciprocal Rank Fusion (RRF): Merge sparse and dense candidate lists using RRF score ranking',
      'Cross-Encoder Re-Ranking: Pass query + top 25 chunks through Cohere/BGE-Reranker for high-precision 0-1 scoring',
      'Context Assembly: Top 3 re-ranked chunks injected into system prompt with markdown citations',
      'LLM Grounded Synthesis: Model answers query strictly conditioned on provided context'
    ],
    mistakes: [
      'Relying solely on vector search for exact ID numbers, error codes, or part numbers (dense models struggle with exact token matches)',
      'Stuffing 50 unranked chunks into the prompt, causing the LLM to suffer from "Lost in the Middle" attention degradation'
    ],
    optimization: 'Hybrid BM25 + Vector Search with Cross-Encoder re-ranking improves RAG answer accuracy from ~64% (Naive RAG) to over 92%.',
    codeSnippet: `// Advanced RAG with Hybrid RRF & Prompt Assembly
export async function assembleRAGPrompt(
  userQuery: string,
  retrievedChunks: { text: string; score: number; source: string }[]
): Promise<string> {
  const contextBlock = retrievedChunks
    .map((c, i) => \`[DOC_\${i + 1}] (Source: \${c.source})\\n\${c.text}\`)
    .join('\\n\\n');

  return \`You are an enterprise AI assistant. Answer the question STRICTLY using the context below.
If the answer cannot be found in the context, respond "I do not have sufficient information to answer this."

=== RETRIEVED CONTEXT ===
\${contextBlock}

=== USER QUERY ===
\${userQuery}

=== GROUNDED ANSWER ===\`;
}`,
    outputDescription: 'Formats high-precision grounded context blocks to eliminate hallucinations.',
    related: ['vector-embeddings-hnsw-indexing', 'react-agents-tool-calling', 'evaluation-hallucination-guardrails']
  },

  // 3. AI Agents
  {
    id: 'react-agents-tool-calling',
    title: 'Autonomous Agents: ReAct Loops & Function Calling',
    kicker: 'Agent Systems / 01',
    group: 'AI Agents',
    difficulty: 'advanced',
    summary: 'Orchestrating autonomous AI agents through Reasoning + Action (ReAct) loops, JSON schema tool calling, and multi-agent delegation.',
    definition: 'AI Agents extend LLMs from passive text generators into active problem solvers. The ReAct (Reasoning + Acting) architecture alternates between generating a Thought (internal reasoning), executing an Action (invoking external APIs, SQL databases, or Python code execution via structured JSON function calling), and receiving an Observation (tool return payload) in a closed loop until the task is resolved.',
    analogy: 'A software engineer troubleshooting an outage: they analyze logs (Thought), run a terminal command to query the database (Action/Tool), read the error stack trace (Observation), formulate a new hypothesis (Thought), and apply the hotfix (Action).',
    steps: [
      'Goal Input: User assigns complex multi-step objective',
      'Thought Generation: LLM plans intermediate sub-goal and determines required tool',
      'Action Execution: LLM outputs valid JSON function call with typed arguments',
      'Tool Execution: Host environment executes API/database call and captures result',
      'Observation Loop: Tool output fed back into LLM context; repeats until Final Answer generated'
    ],
    mistakes: [
      'Allowing unbounded agent loops without max-iteration or token limits, leading to infinite API call loops',
      'Failing to sandbox tool execution environments (e.g. running arbitrary agent-generated code with root OS permissions)'
    ],
    optimization: 'Strict JSON Schema validation (OpenAI Structured Outputs / Pydantic) guarantees 100% schema conformance for downstream function calls.',
    codeSnippet: `// ReAct Autonomous Agent Execution Loop
export interface Tool {
  name: string;
  description: string;
  execute(args: Record<string, any>): Promise<string>;
}

export async function runAgentLoop(
  task: string,
  tools: Tool[],
  maxSteps = 5
): Promise<string> {
  const history: string[] = [\`Task: \${task}\`];

  for (let step = 0; step < maxSteps; step++) {
    const prompt = history.join('\\n') + '\\nThought:';
    const response = await callLLM(prompt); // e.g. "Thought: Need to query SQL -> Action: sqlQuery"
    
    if (response.includes('Final Answer:')) {
      return response.split('Final Answer:')[1].trim();
    }

    const { toolName, args } = parseAction(response);
    const tool = tools.find(t => t.name === toolName);
    const observation = tool ? await tool.execute(args) : 'Tool not found';

    history.push(\`Action: \${toolName}(\${JSON.stringify(args)})\`);
    history.push(\`Observation: \${observation}\`);
  }

  return 'Max execution steps reached.';
}`,
    outputDescription: 'Executes closed-loop Thought -> Action -> Observation cycles.',
    related: ['advanced-rag-retrieval-reranking', 'vector-embeddings-hnsw-indexing', 'prompt-engineering-structured-outputs']
  },

  // 4. Prompt Engineering
  {
    id: 'prompt-engineering-structured-outputs',
    title: 'Prompt Engineering & Structured JSON Output Guarantees',
    kicker: 'Prompting / 01',
    group: 'Prompt Engineering',
    difficulty: 'intermediate',
    summary: 'Techniques for reliable LLM reasoning: Chain-of-Thought (CoT), Few-Shot demonstrations, Constrained Contexts, and grammar-guided JSON schemas.',
    definition: 'Prompt Engineering structures natural language inputs to maximize LLM reasoning fidelity and eliminate non-deterministic parsing failures. Chain-of-Thought prompting encourages step-by-step intermediate deduction before outputting answers. Constrained decoding (Context-Free Grammar / JSON Schema sampling) enforces valid JSON generation at the token sampling level.',
    analogy: 'A formal legal contract template with mandatory check-boxes and constrained response fields: instead of asking for open-ended opinions, the contract forces precise, legally binding answers in an exact standardized format.',
    steps: [
      'System Prompt Design: Establish persona, strict constraints, and error recovery policies',
      'Few-Shot Prompting: Provide 2-3 input-output exemplar pairs to anchor desired formatting and tone',
      'Chain-of-Thought: Instruct model to "Think step-by-step inside <thinking> tags before answering"',
      'JSON Schema Enforcement: Define Pydantic / Zod schema to restrict token logits during sampling',
      'Validation & Self-Correction: Parse output; if validation fails, reflect error back for single-shot repair'
    ],
    mistakes: [
      'Attempting regex-based text parsing on free-form LLM outputs instead of native structured outputs',
      'Writing vague prompts without clear negative constraints ("do not guess", "do not hallucinate")'
    ],
    optimization: 'Grammar-constrained token decoding eliminates JSON syntax errors entirely ($0\\%$ parsing failure rate).',
    codeSnippet: `// Zod Schema-Constrained Output Pattern
import { z } from 'zod';

export const SentimentAnalysisSchema = z.object({
  sentiment: z.enum(['POSITIVE', 'NEGATIVE', 'NEUTRAL']),
  confidenceScore: z.number().min(0).max(1),
  keyEntities: z.array(z.string()),
  reasoning: z.string()
});

export type SentimentAnalysis = z.infer<typeof SentimentAnalysisSchema>;

export const structuredPrompt = \`Analyze customer review text and return ONLY valid JSON matching the schema.
Schema: \${JSON.stringify(SentimentAnalysisSchema.shape)}\`;`,
    outputDescription: 'Guarantees strictly typed JSON responses for seamless backend integration.',
    related: ['react-agents-tool-calling', 'evaluation-hallucination-guardrails', 'advanced-rag-retrieval-reranking']
  },

  // 5. Evaluation & Guardrails
  {
    id: 'evaluation-hallucination-guardrails',
    title: 'LLM Evaluation & RAG Triad Guardrails',
    kicker: 'Evaluation / 01',
    group: 'Evaluation & Guardrails',
    difficulty: 'expert',
    summary: 'Quantifying production AI systems using the RAG Triad (Context Relevance, Groundedness, Answer Relevance), PII masking, and prompt injection defenses.',
    definition: 'AI Application Engineering requires rigorous automated quality evaluation. The RAG Triad framework measures 3 critical metrics: 1. Context Relevance (Are retrieved chunks pertinent?), 2. Groundedness (Is the answer supported by retrieved chunks without hallucinations?), and 3. Answer Relevance (Does the answer address the user query?). Guardrails inspect inputs and outputs for Prompt Injections, Jailbreaks, and PII leakage in real time.',
    analogy: 'A pharmaceutical quality assurance lab: raw ingredients (Retrieved Docs) are tested for purity (Context Relevance), the compound synthesis (LLM Generation) is verified for zero unauthorized toxins (Groundedness/No Hallucination), and the final medication is checked against the doctor prescription (Answer Relevance).',
    steps: [
      'Input Guardrail: Scan user prompt for jailbreak attempts, token bloat, and prompt injection signatures',
      'Retrieval Assessment: Compute Context Relevance score (ratio of useful context tokens to total tokens)',
      'Generation Assessment: Compute Groundedness score by extracting atomic facts and verifying against context',
      'Answer Relevance: Measure semantic similarity between user question and synthesized response',
      'Output Guardrail: Scrub PII (Credit cards, SSNs, API keys) before returning payload to client'
    ],
    mistakes: [
      'Evaluating production LLMs purely with subjective manual "vibe checks" instead of automated LLM-as-a-Judge test suites',
      'Failing to monitor embedding drift and retrieval recall over time'
    ],
    optimization: 'Automated CI/CD RAG evaluation pipelines catch hallucination regressions before PR merges, maintaining >95% groundedness benchmarks.',
    codeSnippet: `// RAG Triad Automated Evaluation Metric
export interface RAGTriadScore {
  contextRelevance: number; // 0.0 to 1.0
  groundedness: number;     // 0.0 to 1.0 (Hallucination check)
  answerRelevance: number;  // 0.0 to 1.0
  isPassing: boolean;
}

export async function evaluateRAGRun(
  query: string,
  context: string,
  answer: string
): Promise<RAGTriadScore> {
  const evalPrompt = \`Evaluate the RAG interaction across 3 metrics (0.0 to 1.0):
1. Context Relevance: Did context contain the answer?
2. Groundedness: Is the answer 100% truthful to context?
3. Answer Relevance: Does the answer directly answer query?

Query: \${query}
Context: \${context}
Answer: \${answer}\`;

  const scores = await callLLMJudge(evalPrompt);
  const isPassing = scores.groundedness >= 0.90 && scores.answerRelevance >= 0.85;
  return { ...scores, isPassing };
}`,
    outputDescription: 'Continuous automated metric evaluation for zero-hallucination production systems.',
    related: ['advanced-rag-retrieval-reranking', 'prompt-engineering-structured-outputs', 'react-agents-tool-calling']
  }
];

export const aiTopicGroups: AiTopicGroup[] = [
  {
    id: 'vector-db',
    name: 'Vector Databases & Embeddings',
    description: 'High-dimensional embeddings, HNSW graph search, Cosine similarity, and vector quantization.',
    badgeColor: 'border-cyan-500/30 text-cyan-400 bg-cyan-500/10',
    topics: aiTopics.filter(t => t.group === 'Vector Databases')
  },
  {
    id: 'rag',
    name: 'RAG Architectures & Retrieval',
    description: 'Hybrid BM25 + Vector search, Reciprocal Rank Fusion, Cross-Encoder Re-Ranking, and citation grounding.',
    badgeColor: 'border-indigo-500/30 text-indigo-400 bg-indigo-500/10',
    topics: aiTopics.filter(t => t.group === 'RAG Architectures')
  },
  {
    id: 'agents',
    name: 'Autonomous AI Agents',
    description: 'ReAct loops (Thought -> Action -> Observation), JSON tool calling, and multi-agent coordination.',
    badgeColor: 'border-amber-500/30 text-amber-400 bg-amber-500/10',
    topics: aiTopics.filter(t => t.group === 'AI Agents')
  },
  {
    id: 'prompting',
    name: 'Prompt Engineering & Schemas',
    description: 'Chain-of-Thought reasoning, Few-Shot prompting, and grammar-constrained JSON schemas.',
    badgeColor: 'border-purple-500/30 text-purple-400 bg-purple-500/10',
    topics: aiTopics.filter(t => t.group === 'Prompt Engineering')
  },
  {
    id: 'eval-guardrails',
    name: 'Evaluation & Guardrails',
    description: 'The RAG Triad (Context, Groundedness, Answer relevance), PII redaction, and prompt injection defense.',
    badgeColor: 'border-emerald-500/30 text-emerald-400 bg-emerald-500/10',
    topics: aiTopics.filter(t => t.group === 'Evaluation & Guardrails')
  }
];

export const getAiTopic = (id: string) => aiTopics.find(t => t.id === id);
